/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    
    dashcode.setupParts();

    // This message checks for common errors with the RSS feed or setup.
    // The handler will hide the split view and display the error message.
    handleCommonErrors(attributes.dataSource,function(errorMessage){
        var splitLayout = document.getElementById('splitLayout1')
        
        if (splitLayout) {
            splitLayout.style.display = 'none';
        }
                       
        showError(errorMessage);
    });
    
    filterItemsWithMedia('episodeList');
}

function toggleMediaView()
{
    var overlayStyle = document.getElementById("overlayContainer").style;
    var mediaView = document.getElementById("media").object;
    
    if (overlayStyle.display == "block") {
        // When toggle the view out, pause the media
        mediaView.pause();
        
        overlayStyle.display = "none";
    } else {
        var listDataSource = dashcode.getDataSource('episodeList');
        var mediaURL = listDataSource.valueForKeyPath('selection.enclosure.$url');

        // Make the overlay and movie visible
        overlayStyle.display = "block";
        
        setTimeout(function(){
            // Set the movie
            mediaView.setSrc(mediaURL);
            
            // Play the video
            mediaView.play();
        },0);
    }
}

// Transformer: listSelectionToSplitterPositionTransformer
// A value transformer which takes the list's hasSelection property (true/false)
// and returns the appropriate position of the splitter
listSelectionToSplitterPositionTransformer = Class.create(DC.ValueTransformer,{
    transformedValue: function(value){
        var newSplitterPosition = 0;
        var splitLayoutElement = document.getElementById('splitLayout1');

        if (value) {
            newSplitterPosition = dashcode.getElementHeight(splitLayoutElement)/2;
        } else {
            newSplitterPosition = dashcode.getElementHeight(splitLayoutElement)-10;
        }
		return newSplitterPosition;
    }
});
